export const APP_ERROR='ERROR_APP';
export const APP_ERROR_RESET='RESET_APP_ERROR';

// eventos faturas
export const REQUEST_FATURAS='FATURAS_REQUEST';
export const RECIEVE_FATURAS='FATURAS_RECIEVE';

//


//eventos clientes
export const REQUEST_CLIENTES='CLIENTE_REQUEST';
export const RECIEVE_CLIENTES='CLIENTE_RECIEVE';
//
//eventos funcionarios
export const REQUEST_FUNCIONARIOS='FUNCIONARIOS_REQUEST';
export const RECIEVE_FUNCIONARIOS='FUNCIONARIOS_RECIEVE';
//

//eventos tipos servicos
export const REQUEST_TIPOS_SERVICOS='TIPOS_SERVICO_REQUEST';
export const RECIEVE_TIPOS_SERVICOS='TIPOS_SERVICO_RECIEVE';
export const ADD_TIPO_SERVICO='ADD_SERVICO';
export const ADDED_TIPO_SERVICO='ADDED_SERVICO';

//

//eventos tipo ocorrencia
export const REQUEST_OCORRENCIAS='OCORRENCIAS_REQUEST';
export const RECIEVE_OCORRENCIAS='OCORRENCIAS_RECIEVE';

//

export const REQUEST_RECIBOS= 'RECIBOS_REQUEST';
export const RECEIVE_RECIBOS='RECIBOS_RECIEVE';


// eventos dados todos
export const REQUEST_DATA='ALL_DATA_REQUEST';
export const RECEIEVE_DATA='ALL_DATA__RECIEVE';
